version: '3.8'

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 127.0.0.0/16
          ip_range: 127.0.0.0/24

services:
  db:
    image: postgres:latest
    container_name: chatservice_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - my_network

  chatservice:
    build:
      context: .
      dockerfile: ../ChatService/Dockerfile
    image: chatservice:latest
    container_name: chatservice
    ports:
      - "${CHAT_SERVICE_PORT}:${CHAT_SERVICE_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - my_network

  client:
    build:
      context: .
      dockerfile: ../ChatService.MessageSenderClient/Dockerfile
    image: client:latest
    container_name: client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - chatservice
    restart: unless-stopped
    networks:
      - my_network

volumes:
  pgdata:
