services:
  chatservice:
    image: chatservice:latest
    container_name: chatservice
    ports:
      - "${CHAT_SERVICE_PORT}:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  client:
    image: client:latest
    container_name: client
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - chatservice
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: chatservice_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  pgdata:
